version: '3.3'
services:
  backend: &backend
    image: geometalab/fog
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      INTERNAL_UPDATE_HOST: 'http://backend:8080/'
      DATABASE_URL: 'postgresql://highfog:highfog@database:5432/fog'
      TEST_DATABASE_URL: 'postgresql://highfog:highfog@test-database:5432/fog'
      FTP_URL: <meteomedia ftp-url>
      FTP_USER: <meteomedia ftp-user>
      FTP_PW: <meteomedia ftp-password>
      EOSM_LOGIN: <eosm login> (ie. "host='host-address' port='port-number' dbname='database name' user='db-user' password='db-password'"
      ELEVATION_SERVICE_URL: <elevation service url>
    depends_on:
      - database
      - test-database
  updater:
    <<: *backend
    entrypoint: dockerize -wait http://backend:8080
    command: python run_scheduled.py
  database:
    image: mdillon/postgis:10
    environment:
      POSTGRES_PASSWORD: 'highfog'
      POSTGRES_USER: 'highfog'
      POSTGRES_DB: 'fog'
  test-database:
    image: mdillon/postgis:10
    environment:
      POSTGRES_PASSWORD: 'highfog'
      POSTGRES_USER: 'highfog'
      POSTGRES_DB: 'fog'
  nginx:
    image: geometalab/fog-proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    environment:
      VIRTUAL_HOST: 'localhost,?<domain>.+$$'
      EXTERNAL_HIGHFOG_SERVICE_URL: 'http://localhost:8090/api/'
      FOG_TILES_URL: 'http://sifsv-80047.hsr.ch/tiles/'
